# Generated by Django 5.1.4 on 2025-05-31 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('ImageID', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=255)),
                ('FilePath', models.CharField(max_length=255)),
                ('UploadDateTime', models.DateTimeField(auto_now_add=True)),
                ('ImageFile', models.ImageField(upload_to='')),
                ('FileSize', models.BigIntegerField(blank=True, null=True)),
                ('ImageFormat', models.CharField(blank=True, max_length=10, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionResult',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False)),
                ('Labels', models.TextField()),
                ('ConfidenceScores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ProcessedDateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('ProcessingTime', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('MaskImageBase64', models.TextField(blank=True, null=True)),
                ('ImageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image')),
            ],
        ),
    ]
