# Generated by Django 4.2.7 on 2023-11-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionResult',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False)),
                ('Labels', models.TextField()),
                ('ConfidenceScores', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.AlterField(
            model_name='image',
            name='ImageFile',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='recognitionresult',
            name='ImageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image'),
        ),
    ]
